[package]
name = "fan-control"
version = "0.1.0"
edition = "2021"
license = "MIT"
exclude = ["config"]

[workspace]
members = [
    "data",
    "hardware",
    "ui",
    #"tray",
    "experimental",
]


[dependencies]
data.workspace = true
hardware.workspace = true
ui.workspace = true
clap.workspace = true
log.workspace = true
env_logger.workspace = true

[dev-dependencies]


[workspace.dependencies]
fan-control = { version = "0.1", path = "." }
data = { version = "0.1", path = "data" }
hardware = { version = "0.1", path = "hardware" }
ui = { version = "0.1", path = "ui" }
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
toml = "0.7"
env_logger = "0.10"
log = "0.4"
