[package]
name = "fan-control"
version = "0.1.0"
edition = "2021"
license = "MIT"


[workspace]
members = [
    "data",
    "hardware",
    "ui",
    #"tray",
    "experimental",
    "light_enum"
]


[dependencies]
data.workspace = true
hardware.workspace = true
ui.workspace = true
clap.workspace = true



[workspace.dependencies]
fan-control = { version = "0.1", path = "." }
data = { version = "0.1", path = "data" }
hardware = { version = "0.1", path = "hardware" }
ui = { version = "0.1", path = "ui" }
clap = { version = "4.3.8", features = ["derive"] }
serde = { version = "1.0.181", features = ["derive"] }
serde_json = "1.0.104"
toml = "0.7.6"
