[env]
LMSENSORS_STATIC = "1"
LMSENSORS_INCLUDE_DIR = { value = "target/libsensors_build/include", relative = true }
LMSENSORS_LIB_DIR = { value = "target/libsensors_build/lib", relative = true }
RUST_LOG = "fan_control=debug,data=info,hardware=debug,ui=debug"
#RUST_BACKTRACE = "1"