[[behaviors]]

[behaviors.TempMath]
name = "max"
kind = "Max"
input = [
    "temp1",
    "temp2",
]

[[behaviors]]

[behaviors.Graph]
name = "graph1"
input = "max"
output = ["control1"]

[[behaviors.Graph.coord]]
temp = 10
percent = 10

[[behaviors.Graph.coord]]
temp = 50
percent = 30

[[behaviors.Graph.coord]]
temp = 90
percent = 100

[[behaviors]]

[behaviors.Flat]
name = "flat1"
value = 50
output = ["control2"]

[[behaviors]]

[behaviors.Linear]
name = "graph1"
input = "temp3"
output = ["control3"]

[behaviors.Linear.min]
temp = 10
percent = 10

[behaviors.Linear.max]
temp = 70
percent = 100

[[behaviors]]

[behaviors.Target]
name = "graph1"
input = "temp3"
output = ["control4"]

[behaviors.Target.ideal]
temp = 40
percent = 10

[behaviors.Target.load]
temp = 70
percent = 100
