[[CustomTemp]]
name = "max"
kind = "Max"
input = [
    "temp1",
    "temp2",
]

[[Graph]]
name = "graph1"
input = "max"
output = ["control1"]

[[Graph.Coord]]
temp = 10
percent = 10

[[Graph.Coord]]
temp = 50
percent = 30

[[Graph.Coord]]
temp = 90
percent = 100

[[Flat]]
name = "flat1"
value = 50
output = ["control2"]

[[Flat]]
name = "flat2"
value = 100
output = []

[[Linear]]
name = "graph1"
min_temp = 10
min_speed = 10
max_temp = 70
max_speed = 100
input = "temp3"
output = ["control3"]

[[Target]]
name = "graph1"
idle_temp = 40
idle_speed = 10
load_temp = 70
load_speed = 100
input = "temp3"
output = ["control4"]
