[[CustomTemp]]
name = "max"
kind = "Max"
input = [
    "temp1",
    "temp2",
]

[[Graph]]
name = "graph1"
input = "max"
output = ["control1"]

[[Graph.coord]]
temp = 10
percent = 10

[[Graph.coord]]
temp = 50
percent = 30

[[Graph.coord]]
temp = 90
percent = 100

[[Flat]]
name = "flat1"
value = 50
output = ["control2"]

[[Flat]]
name = "flat2"
value = 100
output = []

[[Linear]]
name = "graph1"
minTemp = 10
minSpeed = 10
maxTemp = 70
maxSpeed = 100
input = "temp3"
output = ["control3"]

[[Target]]
name = "graph1"
idleTemp = 40
idleSpeed = 10
loadTemp = 70
loadSpeed = 100
input = "temp3"
output = ["control4"]
