[[Control]]
name = "control1"
id = "nct6798-isa-0290-pwm1"
input = "flat1"
auto = false

[[Control]]
name = "control2"
id = "nct6798-isa-0290-pwm2"
input = "linear1"
auto = false

[[Control]]
name = "control2"
id = "nct6798-isa-0290-pwm4"
input = "target1"
auto = false

[[Flat]]
name = "flat1"
value = 50

[[Linear]]
name = "linear1"
minTemp = 10
minSpeed = 10
maxTemp = 70
maxSpeed = 100
input = "custom_temp"



[[Target]]
name = "target1"
idleTemp = 40
idleSpeed = 10
loadTemp = 70
loadSpeed = 100




[[CustomTemp]]
name = "custom_temp"
kind = "Max"
input = [
    "temp1",
    "temp2",
]





[[Temp]]
name = "temp1"
id = "nct6798-isa-0290-temp2_input"

[[Temp]]
name = "temp2"
id = "nct6798-isa-0290-temp3_input"

[[Temp]]
name = "temp3"
id = "nct6798-isa-0290-temp4_input"