[[controls]]
name = "control1"

[[controls]]
name = "control2"

[[controls]]
name = "control3"

[[controls]]
name = "control4"

[[temps]]
name = "temp1"

[[temps]]
name = "temp2"

[[temps]]
name = "temp3"
