[[Control]]
name = "pwm1 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm1"

[[Control]]
name = "pwm2 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm2"

[[Control]]
name = "pwm3 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm3"

[[Control]]
name = "pwm4 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm4"

[[Control]]
name = "pwm5 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm5"

[[Control]]
name = "pwm6 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm6"

[[Fan]]
name = "fan1 nct6798-isa-0290"
id = "nct6798-isa-0290-fan1_input"

[[Fan]]
name = "fan2 nct6798-isa-0290"
id = "nct6798-isa-0290-fan2_input"

[[Fan]]
name = "fan3 nct6798-isa-0290"
id = "nct6798-isa-0290-fan3_input"

[[Fan]]
name = "fan4 nct6798-isa-0290"
id = "nct6798-isa-0290-fan4_input"

[[Fan]]
name = "fan5 nct6798-isa-0290"
id = "nct6798-isa-0290-fan5_input"

[[Fan]]
name = "fan6 nct6798-isa-0290"
id = "nct6798-isa-0290-fan6_input"

[[Fan]]
name = "fan7 nct6798-isa-0290"
id = "nct6798-isa-0290-fan7_input"

[[Temp]]
name = "temp1 jc42-i2c-1-1a"
id = "jc42-i2c-1-1a-temp1_input"

[[Temp]]
name = "SYSTIN nct6798-isa-0290"
id = "nct6798-isa-0290-temp1_input"

[[Temp]]
name = "CPUTIN nct6798-isa-0290"
id = "nct6798-isa-0290-temp2_input"

[[Temp]]
name = "AUXTIN0 nct6798-isa-0290"
id = "nct6798-isa-0290-temp3_input"

[[Temp]]
name = "AUXTIN1 nct6798-isa-0290"
id = "nct6798-isa-0290-temp4_input"

[[Temp]]
name = "AUXTIN2 nct6798-isa-0290"
id = "nct6798-isa-0290-temp5_input"

[[Temp]]
name = "AUXTIN3 nct6798-isa-0290"
id = "nct6798-isa-0290-temp6_input"

[[Temp]]
name = "PECI Agent 0 Calibration nct6798-isa-0290"
id = "nct6798-isa-0290-temp7_input"

[[Temp]]
name = "PCH_CHIP_CPU_MAX_TEMP nct6798-isa-0290"
id = "nct6798-isa-0290-temp8_input"

[[Temp]]
name = "PCH_CHIP_TEMP nct6798-isa-0290"
id = "nct6798-isa-0290-temp9_input"

[[Temp]]
name = "PCH_CPU_TEMP nct6798-isa-0290"
id = "nct6798-isa-0290-temp10_input"

[[Temp]]
name = "TSI0_TEMP nct6798-isa-0290"
id = "nct6798-isa-0290-temp11_input"

[[Temp]]
name = "Composite nvme-pci-0500"
id = "nvme-pci-0500-temp1_input"

[[Temp]]
name = "temp1 iwlwifi_1-virtual-0"
id = "iwlwifi_1-virtual-0-temp1_input"

[[Temp]]
name = "temp1 jc42-i2c-1-1b"
id = "jc42-i2c-1-1b-temp1_input"

[[Temp]]
name = "Tctl k10temp-pci-00c3"
id = "k10temp-pci-00c3-temp1_input"

[[Temp]]
name = "Tccd1 k10temp-pci-00c3"
id = "k10temp-pci-00c3-temp3_input"

[[Temp]]
name = "Composite nvme-pci-0100"
id = "nvme-pci-0100-temp1_input"

[[Temp]]
name = "Sensor 1 nvme-pci-0100"
id = "nvme-pci-0100-temp2_input"

[[Temp]]
name = "Sensor 2 nvme-pci-0100"
id = "nvme-pci-0100-temp3_input"

[[Temp]]
name = "Sensor 8 nvme-pci-0100"
id = "nvme-pci-0100-temp9_input"
