[[Control]]
name = "CPU"
id = "/lpc/nct6798d/control/1"
input = "linear1"
auto = false

[[Control]]
name = "Fan #3"
id = "/lpc/nct6798d/control/2"
input = "flat1"
auto = false

[[Control]]
name = "Fan #4"
id = "/lpc/nct6798d/control/3"
input = "flat1"
auto = false


[[Control]]
name = "GPU Fan 1"
id = "/gpu-nvidia/0/control/1"
input = "target1"
auto = false


[[Control]]
name = "GPU Fan 2"
id = "/gpu-nvidia/0/control/2"
input = "target1"
auto = false



[[Flat]]
name = "flat1"
value = 50

[[Linear]]
name = "linear1"
input = "CPU"
minTemp = 10
minSpeed = 10
maxTemp = 70
maxSpeed = 100



[[Target]]
name = "target1"
input = "GPU"
idleTemp = 40
idleSpeed = 10
loadTemp = 70
loadSpeed = 100




[[CustomTemp]]
name = "CPU"
kind = "Average"
input = [
    "Core (Tctl/Tdie)",
    "CCD1 (Tdie)",
]

[[CustomTemp]]
name = "GPU"
kind = "Average"
input = [
    "GPU Core",
    "GPU Hot Spot"
]



[[Temp]]
name = "Core (Tctl/Tdie)"
id = "/amdcpu/0/temperature/2"

[[Temp]]
name = "CCD1 (Tdie)"
id = "/amdcpu/0/temperature/4"

[[Temp]]
name = "GPU Core"
id = "/gpu-nvidia/0/temperature/0"

[[Temp]]
name = "GPU Hot Spot"
id = "/gpu-nvidia/0/temperature/2"