[[Control]]
name = "control1"
input = "linear1"
active = true

[[Linear]]
name = "linear1"
minTemp = 10
minSpeed = 10
maxTemp = 70
maxSpeed = 100
input = "custom_temp"

[[CustomTemp]]
name = "custom_temp"
kind = "Average"
input = [
    "temp1",
    "temp2",
]

[[Temp]]
name = "temp1"
id = "coretemp-isa-0000-temp3_input"

[[Temp]]
name = "temp2"
id = "coretemp-isa-0000-temp2_input"