Graph = []

[[Control]]
name = "control2"
input = "target1"
active = false

[[Control]]
name = "control1"
id = "control1"
input = "linear1"
active = true

[[Fan]]
name = "fan1"
id = "fan1"

[[Temp]]
name = "temp1"
id = "temp1"

[[Temp]]
name = "temp2"
id = "temp2"

[[CustomTemp]]
name = "custom_temp"
kind = "Average"
input = [
    "temp1",
    "temp2",
]

[[Flat]]
name = "flat1"
value = 50

[[Linear]]
name = "linear1"
minTemp = 10
minSpeed = 10
maxTemp = 70
maxSpeed = 100
input = "custom_temp"

[[Target]]
name = "target1"
idleTemp = 40
idleSpeed = 10
loadTemp = 70
loadSpeed = 100
