[[Control]]
name = "pwm1 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm1"
input = "linear1"
active = true

[[Control]]
name = "pwm2 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm2"
input = "flat1"
active = true

[[Control]]
name = "pwm3 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm3"
input = "flat1"
active = true





[[Flat]]
name = "flat1"
value = 100

[[Linear]]
name = "linear1"
input = "CPU"
minTemp = 10
minSpeed = 10
maxTemp = 70
maxSpeed = 100



[[Target]]
name = "target1"
input = "GPU"
idleTemp = 40
idleSpeed = 10
loadTemp = 70
loadSpeed = 100




[[CustomTemp]]
name = "CPU"
kind = "Average"
input = [
    "AUXTIN1 nct6798-isa-0290",
    "CPUTIN nct6798-isa-0290",
]

[[CustomTemp]]
name = "GPU"
kind = "Average"
input = [
    "GPU Core",
    "GPU Hot Spot"
]



[[Temp]]
name = "AUXTIN1 nct6798-isa-0290"
id = "nct6798-isa-0290-temp4_input"
[[Temp]]
name = "CPUTIN nct6798-isa-0290"
id = "nct6798-isa-0290-temp2_input"

[[Temp]]
name = "GPU Core"

[[Temp]]
name = "GPU Hot Spot"