CustomTemp = []
Graph = []
Flat = []
Linear = []
Target = []

[[Control]]
name = "control1"
id = "control1"
active = true

[[Control]]
name = "control2"
id = "control2"
active = true

[[Fan]]
name = "fan1"
id = "fan1"

[[Temp]]
name = "temp1"
id = "temp1"

[[Temp]]
name = "temp2"
id = "temp2"
