

[[Control]]
name = "pwm2 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm2"
input = "flat1"
active = true

[[Control]]
name = "pwm3 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm3"
input = "flat2"
active = true

[[Control]]
name = "pwm4 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm4"
input = "flat2"
active = true


[[Flat]]
name = "flat1"
value = 100

[[Flat]]
name = "flat2"
value = 0