[package]
name = "tray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.10.0"
image = "0.24.7"
tao = "0.22.2"
tray-icon = "0.9.0"
