[package]
name = "ui"
version = "0.1.0"
edition = "2021"


[dependencies]
data.workspace = true
hardware.workspace = true
log.workspace = true
i18n-embed.workspace = true
i18n-embed-fl.workspace = true
rust-embed.workspace = true
lazy_static.workspace = true

[dependencies.iced]
version = "0.10"
features = [
    #"svg", 
    "advanced",
    "smol"
]