[package]
name = "ui"
version = "0.1.0"
description = "Ui implementation of fan-control"
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true


[dependencies]
data.workspace = true
hardware.workspace = true
log.workspace = true
i18n-embed.workspace = true
i18n-embed-fl.workspace = true
rust-embed.workspace = true
lazy_static.workspace = true
once_cell.workspace = true
cargo-packager-resource-resolver.workspace = true
derive_more.workspace = true
tokio = { version = "1.35", features = ["time"] }
[dependencies.libcosmic]
#git = "https://github.com/wiiznokes/libcosmic"
git = "https://github.com/pop-os/libcosmic"
rev = "1bd39b17ae7c97934ea214028cd31c578b589e3e"
#branch = "master"
default-features = false
features = [
    "smol",
    "wgpu",
    "winit",
    "tokio",
    #"a11y",
    #"debug",
    #"serde-keycode",
    #"wayland",
]
