name: Release

on:
  workflow_dispatch:
    inputs:
      is_nightly:
        description: "Is nightly"
        required: true
        default: true
        type: boolean
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  upload-artifacts:
    uses: ./.github/workflows/upload_artifacts.yml
  
  publish:
    needs: upload-artifacts
    runs-on: ubuntu-latest

    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "PKG_VERSION=$(cargo pkgid | grep -oP '@\K\d+\.\d+\.\d+')" >> $GITHUB_ENV
          gh release delete nightly --yes || true
          git push origin :nightly || true
      - if: ${{ github.event.inputs.is_nightly  == 'true' }}
        run: |
          echo "TAG_NAME=nightly" >> $GITHUB_ENV
          echo "PRERELEASE=--prerelease" >> $GITHUB_ENV
      - if: ${{ github.event.inputs.is_nightly == 'false' }}
        run: |
          echo "TAG_NAME=v${{ env.PKG_VERSION }}" >> $GITHUB_ENV

      - uses: actions/download-artifact@v3
      
      - name: Publish release
        run: |
          gh release create ${{ env.TAG_NAME }} ${{ env.PRERELEASE }} --title "${{ env.TAG_NAME }}" --generate-notes ./fan-control*/*