name: 'Upload artifacts'
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  upload_linux_artifact:
    runs-on: "ubuntu-latest"
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@master

      - name: Make libsensors
        run: make libsensors

      - name: Build release
        run: cargo build --release
        
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: fan-control
          path: target/release/fan-control
          
  # TODO: experiment cross compile: linux -> win
  upload_windows_artifact:
    runs-on: "windows-latest"
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@master

      - name: Make lhm
        run: make lmh

      - name: Build release
        run: cargo build --release

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: fan-control
          path: target/release/fan-control